name = "Basins"
uuid = "7e5b28ef-eee2-49be-86fd-c343c6921134"
authors = ["Alexandre Wagemakers"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
